#
# Build configuration for Circle CI
#

general:
    artifacts:
        - /home/ubuntu/myTaxiDemoApp/app/build/outputs/apk/

machine:
    java:
        version: oraclejdk8
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

dependencies:
    pre:
        - echo y | android update sdk --no-ui --all --filter "platform-tools, tools"
        - echo y | android update sdk --no-ui --all --filter "android-26"
        - echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"
        - echo y | android update sdk --no-ui --all --filter "extra-android-support"
        - echo y | android update sdk --no-ui --all --filter "build-tools-26.0.2"
    override:
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
    checkout:
        post:
        - cp -r licenses/. /usr/local/android-sdk-linux/licenses

test:
  override:
    # start the emulator
    - emulator -avd circleci-android26 -no-audio -no-window:
        background: true
        parallel: true
    # wait for it to have booted
    - circle-android wait-for-boot
    # unlock the emulator screen
    - sleep 30
    - adb shell input keyevent 82
    # run tests  against the emulator.
    - ./gradlew connectedAndroidTest -PdisablePreDex
    # copy the build outputs to artifacts
    - cp -r app/build/outputs $CIRCLE_ARTIFACTS
    # copy the test results to the test results directory.
    - cp -r app/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS